# Site settings
baseurl: "/docsearch" # the subpath of your site, e.g. /blog/
host: 0.0.0.0

# OpenGraph / Twitter
title: DocSearch
description: Algolia DocSearch is the easiest way to add search to your documentation. Just send us your URL, and we'll send you the implementation code.
tagline: DocSearch
card_image: /path/to/card.jpg
card_image_width: 1200
card_image_height: 600
twitter_username: algolia
github_username: algolia

# Navigation
navigation:
  -
    text: Documentation
    url: /documentation/
  -
    text: About
    url: /about/

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true

  coderay_wrap: div
  coderay_line_numbers: nil
  coderay_css: style

# Assets
sass:
  sass_dir: css
